server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.55.35.77:3306/forum?serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123$MYSQL123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #拒绝空显示
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  redis:
    database: 0
    host: 114.55.35.77
    # boot拥有两种集成redis的方式，一种是Jedis(非线程安全的，除非使用连接池),一种是Lettuce基于Netty的连接实例
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
      shutdown-timeout: 100ms

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰转换
    map-underscore-to-camel-case: true

    #文件上传路径
forum:
  file:
    upload: /etc/nginx/www/chaos-forum/upload/
    static-url: http://114.55.35.77/images/



