spring:
  datasource:
    url: jdbc:mysql://114.55.35.77:3306/forum?serverTimezone=UTC
    username: root
    password: mysql123$MYSQL123
    driver-class-name: com.mysql.cj.jdbc.Driver


  #拒绝空显示
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰转换
    map-underscore-to-camel-case: true

    #文件上传路径
forum:
  file:
    upload: /etc/nginx/www/chaos-forum/upload/
    static-url: http://114.55.35.77/images/

server:
  port: 8080
