spring:
  datasource:
    url: jdbc:mysql://114.55.35.77:3306/forum?serverTimezone=UTC
    username: root
    password: mysql123$MYSQL123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰转换
    map-underscore-to-camel-case: true

    #文件上传路径
forum:
  file:
    upload: E:/project/chaos-forum/backend/src/main/resources/static/
    static-url: http://10.0.18.37:8080/image/
    #upload: /home/image/
    #static-url: http://114.55.35.77:8080/image/


